//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAttachment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int InvoiceId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
