//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcInvoiceDbEntities : DbContext
    {
        public MvcInvoiceDbEntities()
            : base("name=MvcInvoiceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Country_SDIC> Country_SDIC { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<FileAttachment> FileAttachment { get; set; }
        public virtual DbSet<InvoiceContractorsData> InvoiceContractorsData { get; set; }
        public virtual DbSet<InvoicePosition> InvoicePosition { get; set; }
        public virtual DbSet<TaxRate> TaxRate { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Summary> Summary { get; set; }
        public virtual DbSet<RssSiteChannel> RssSiteChannel { get; set; }
        public virtual DbSet<RssChannel_SDIC> RssChannel_SDIC { get; set; }
        public virtual DbSet<ParameterGlobal> ParameterGlobal { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostCategory_SDIC> PostCategory_SDIC { get; set; }
        public virtual DbSet<BankAccount> BankAccount { get; set; }
        public virtual DbSet<Currency_SDIC> Currency_SDIC { get; set; }
        public virtual DbSet<Company> Company { get; set; }
    }
}
