//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.FileAttachment = new HashSet<FileAttachment>();
            this.InvoicePosition = new HashSet<InvoicePosition>();
            this.Summary = new HashSet<Summary>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> RecieveDate { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public bool IsNet { get; set; }
        public bool IsForeignCustomer { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> AmountNetPln { get; set; }
        public Nullable<decimal> AmountNetCurrency { get; set; }
        public Nullable<decimal> AmountTaxPln { get; set; }
        public Nullable<decimal> AmountTaxCurrency { get; set; }
        public Nullable<decimal> AmountGrossPln { get; set; }
        public Nullable<decimal> AmountGrossCurrency { get; set; }
        public int CompanyId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public int InvoiceContractorsDataId { get; set; }
        public string DataSearch { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileAttachment> FileAttachment { get; set; }
        public virtual InvoiceContractorsData InvoiceContractorsData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePosition> InvoicePosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Summary> Summary { get; set; }
        public virtual Currency_SDIC Currency_SDIC { get; set; }
        public virtual Company Company { get; set; }
    }
}
